/*
 Ebis Tracking Object
 Copyright 2017 LOCKON CO.,LTD.
 @external Ebis
*/
(function(){function l(a,b){k.call(this,a,b);this.f()}function n(a,b,c){this.l=a;this.s=b;this.T=c;this.j="cid pid o1id o2id o3id o4id o5id m1id a1id".split(" ")}function g(a,b){k.call(this,a,b);this.f()}function m(a,b){k.call(this,a,b);this.f()}function k(a,b){this.M=a;this.data=b}function p(){this.J={type:"ebisAccessTypes",other1:"ebisOther1",other2:"ebisOther2",other3:"ebisOther3",other4:"ebisOther4",other5:"ebisOther5",member_name:"ebisMember",amount:"ebisAmount",page_id:"ebisPageID",argument:"argument",
referrer:"referrer",pageurl:"pageurl",pagetitle:"pagetitle",user_agent:"ebisUA",ad_id:"ai",tag_id:"tag_id",dn:"dn",js:"js",td:"td",otd:"otd",xd:"xd",cid:"argument",pid:"ebisPageID",o1id:"ebisOther1",o2id:"ebisOther2",o3id:"ebisOther3",o4id:"ebisOther4",o5id:"ebisOther5",m1id:"ebisMember",a1id:"ebisAmount",rand:"ebisRand"}}function d(a,b,c,e){this.m=b;this.G="//ac.ebis.ne.jp/rec.php?ebisV=1.1";this.Qa=["click","pv","search"];this.qa="pv,search";this.h={contents:"//imp.ebis.ne.jp/imp.php"};this.s=s;
this.startTime=this.s.getTime();this.g=e||[];this.c=null;this.Ra=a||[];this.b=[];this.d={};this.ga=2E3;this.Z=new p;this.ta=c||[];this.ka=20}function f(){}var s=new Date;f.prototype.S=function(a,b){function c(a,b){var c=void 0!==a?a.split(","):[];void 0!==b&&Array.prototype.push.apply(c,b.split(","));c=c.filter(function(a,b,c){return c.indexOf(a)==b});return c.join(",")}for(var e in b)b.hasOwnProperty(e)&&(a[e]="type"==e?c(a[e],b[e]):b[e]);return a};f.prototype.I=function(a){return this.S({},a)};
f.prototype.ua=function(a){var b={},c;for(c in a)a.hasOwnProperty(c)&&(b[c]="function"==typeof a[c]?a[c]:encodeURIComponent(a[c]));return b};f.prototype.Aa=function(a){return Object.keys(a).map(function(b){return encodeURIComponent(b)+"="+encodeURIComponent(a[b])}).join("&")};f.prototype.w=function(a){a=a.dataset;var b={},c;for(c in a)a.hasOwnProperty(c)&&(b[c]=a[c]);return b};f.prototype.B=function(a,b){function c(){}c.prototype=b.prototype;a.Ua=b.prototype;a.prototype=new c};f.prototype.o=function(a,
b){return a+"_"+b};d.prototype.init=function(a){this.c=a.argument;if(!this.c)throw"Argument not set";this.G=a.tagHost||this.G;this.h=a.alternativeHost||this.h;0<=this.g.indexOf(this.c)?this.V():(this.g.push(this.c),this.V(),this.b=this.Ra,this.xa(this.c)?this.v():void 0!==a.auto&&!0!=a.auto||this.push({argument:this.c}),this.ba(a))};d.prototype.X=function(a){this.b.push(a)};d.prototype.push=function(a){this.X(a);this.v()};d.prototype.V=function(){this.d={referrer:document.referrer,pagetitle:document.title,
pageurl:document.URL,user_agent:window.navigator.userAgent};this.la();this.H&&this.Ha()};d.prototype.la=function(){var a=this.d.user_agent||"";this.H=-1!=a.indexOf("Mac")&&-1!=a.indexOf("AppleWebKit")&&-1==a.indexOf("Chrome")&&-1==a.indexOf("Windows")};d.prototype.Ha=function(){var a=this.A(),b=this.Ba();b&&(a&&a!=b&&(this.d.otd=a),a=b,this.Y(a));this.d.td=a;this.m.u&&this.ia()};d.prototype.La=function(a,b){return this.wa(a)&&(b||this.Na()||this.Ma(a))};d.prototype.wa=function(a){var b=void 0!==a.cid;
return(a=b?a.cid:a.argument)?a===this.c||b&&0<=this.g.indexOf(a)?!0:!1:!1};d.prototype.Na=function(){return this.m.Ca||this.m.pa||this.H&&this.m.u&&this.F?!0:!1};d.prototype.Ma=function(a){return-1!==a.type.indexOf("click")};d.prototype.ia=function(){var a=parseInt(localStorage.getItem(f.prototype.o("_ebts",this.c)));if(isNaN(a)||18E5<this.startTime-a)this.F=!0};d.prototype.Ea=function(){for(var a="",b=0;b<this.g.length;b++){var c=localStorage.getItem(f.prototype.o("_ebdm",this.g[b]));null!==c&&(0<
a.length&&(a+="|"),a+=c)}a&&(this.L=RegExp(a))};d.prototype.va=function(a){return(new Date).getTime()+"."+a};d.prototype.oa=function(a,b){return this.Z.ea(a,b)};d.prototype.K=function(a,b){var c=a.js?document.createElement("script"):new window.Image(1,1);a.callback&&"function"==typeof a.callback&&(this.i=c,c.onload=c.onerror=c.onabort=a.callback,this.timeout=setTimeout(c.onload,this.ga));c.src=this.oa(a,b);if(a.js){c.type="text/javascript";c.async=!0;var e=document.getElementsByTagName("script")[0];
e.parentNode.insertBefore(c,e)}};d.prototype.cb=function(a){this.Y(a.t);void 0!==a.x&&this.Oa(a.x,a.a)};d.prototype.Oa=function(a,b){var c=f.prototype.o("_ebts",b);localStorage.setItem(f.prototype.o("_ebdm",b),a);localStorage.setItem(c,this.startTime);this.F=!1};d.prototype.P=function(){for(var a=document.cookie.split("; "),b=0;b<a.length;b++){var c=a[b].split("=");if("_ebtd"==c[0])return c[1]}return null};d.prototype.A=function(){var a=this.P();if(!a)return"";if(!this.k){var b=a.substring(0,a.indexOf("."));
this.k=this.Q()[b]}return a.substring(a.indexOf(".")+1)};d.prototype.Ga=function(a,b){document.cookie="_ebtd="+a+"; path=/ ; expires="+(new Date((new Date).getTime()+63072E6)).toUTCString()+"; domain="+b};d.prototype.Q=function(){for(var a=[],b=document.domain,c=b.length;-1!=c;)c=b.lastIndexOf(".",c-1),a.push(b.substring(c+1));return a};d.prototype.Y=function(a){for(var b=this.Q(),c=1;c<b.length+1;c++){var e=c+"."+a;this.Ga(e,b[c]);if(this.P()==e){this.d.td=a;this.k=b[c];break}}};d.prototype.W=function(a){if(/[?&]_ebx=[^&#]*/.test(a))return!1;
this.r=this.A();if(!this.r||!this.k||(a=(a=a.match(/^https?\:\/\/([^\/?#]+)/i))&&a[1])&&-1<a.indexOf(this.k))return!1;this.Ea();return this.L?this.L.test(a):!1};d.prototype.link=function(a){return(this.r=this.A())?this.D(a):a};d.prototype.O=function(){return this.r+"."+parseInt((new Date).getTime()/100).toString(36)};d.prototype.D=function(a){var b={};b._ebx=this.O();return this.Z.ca(a,b)};d.prototype.Ba=function(){var a=/[?&]_ebx=([^&#]*)/.exec(document.URL);if(null!==a){a=a[1];try{var b=a.lastIndexOf("."),
c=parseInt(a.substring(b+1),36)}catch(e){return null}return!c||1200<parseInt((new Date).getTime()/100)-c?null:a.substring(0,b)}};d.prototype.ma=function(a,b){a=decodeURIComponent(a);for(var c=a.split(","),e=[],h=0;h<c.length;h++)0<=b.indexOf(c[h])&&e.push(c[h]);return e.join(",")};d.prototype.aa=function(a){a=f.prototype.I(a);a.type=this.ma(a.type,this.Qa);a.type&&(this.H&&(a.js="cb",this.F&&(a.xd=1)),this.K(a,this.G))};d.prototype.$=function(a){for(var b in this.h)if(this.h.hasOwnProperty(b)&&0<=
a.type.indexOf(b)){var c=f.prototype.I(a);c.type=b;this.K(c,this.h[b])}};d.prototype.v=function(){for(var a=[],b=0;b<this.b.length;b++){var c=this.b[b],e;a:{e=c;var h=void 0;for(h in e)if(e.hasOwnProperty(h)&&"argument"!==h){e=!0;break a}e=!1}h=this.ya(c,b);this.La(h,e)?(this.aa(h),this.$(h)):e&&a.push(c)}this.b=a};d.prototype.ya=function(a,b){var c=f.prototype.S(a,this.d),c=f.prototype.ua(c);void 0===c.type&&(c.type=this.qa);this.za(c)&&(c.type+=",click");c.rand=this.va(b);return c};d.prototype.za=
function(a){return void 0!==a.cid?!1:/[?&][dr]mai=/.test(this.d.pageurl)};d.prototype.xa=function(a){for(var b=0;b<this.b.length;b++)if(this.b[b].argument&&this.b[b].argument==a)return!0;return!1};d.prototype.ba=function(a){var b=function(a,e,h){return function(){if("interactive"!=document.readyState&&"complete"!=document.readyState)setTimeout(b,this.ka);else for(var d=0;d<h.length;d++)new h[d](a,e)}}(this,a,this.ta);b()};p.prototype.na=function(a){return this.J[a]?this.J[a]:""};p.prototype.ea=function(a,
b){var c="",e=[],d=!1;b.match(/\?/)&&(d=!0);for(var f in a)if(a.hasOwnProperty(f)){var g=this.na(f);0<g.length&&0>e.indexOf(g)&&(d?c+="&":(c+="?",d=!0),e.push(g),c+=g+"="+a[f])}return b+c};p.prototype.ca=function(a,b){var c="",e=a,d=a.indexOf("#");-1!=d&&(c=a.substring(d+1),e=a.substring(0,d));var d=-1==e.indexOf("?")?"?":"&",g=f.prototype.Aa(b);return e+d+g+(c?"#"+c:"")};k.prototype.f=function(){};f.prototype.B(m,k);m.prototype.f=function(){this.event="click";this.tagName=this.data.fa?this.data.fa:
"ebis_button_trigger";var a=this.ha();this.Fa(a);this.M.Ta=function(a,c,e,d,f,g,t,k,l,m){window.ebis.push({type:"pv",argument:c,page_id:e,member_name:d||"",amount:m||"",other1:f||"",other2:g||"",other3:t||"",other4:k||"",other5:l||"",Sa:function(){a.href&&(location.href=a.href)}});return!1}};m.prototype.ha=function(){for(var a=[],b=document.getElementsByClassName(this.tagName),c=0;c<b.length;c++){var e=f.prototype.w(b[c]),d;for(d in e)e.hasOwnProperty(d)&&e[d]==this.data.argument&&a.push(b[c])}return a};
m.prototype.Fa=function(a){function b(a){var b=f.prototype.w(this);b.type||(b.type="pv");this.target&&"_blank"==this.target.toLowerCase()||(a.preventDefault(),b.callback=function(a,b){return function(){var a=window.ebis;clearTimeout(a.timeout);a.i&&a.i.onload&&(a.i.onload=a.i.onerror=a.i.onabort=null);location.href=b.href}}(b,this));window.ebis.push(b)}for(var c=0;c<a.length;c++)a[c].addEventListener?a[c].addEventListener(this.event,b,!1):a[c].attachEvent&&a[c].attachEvent("on"+this.event,b)};f.prototype.B(g,
k);g.prototype.f=function(){this.event="scroll";this.C=!1;this.p=[];this.q=[];if(this.ja()){this.Ka();this.n=[];this.R=1;this.e={};this.da();var a=this.U();this.N(a);return this}};g.prototype.sa="ebis_tag_trigger";g.prototype.Ka=function(){for(var a=this.data.T||"o1id",b=0;b<this.p.length;b++)this.q.push(new n(this.p[b],this.M.s,a))};g.prototype.ja=function(){for(var a=document.getElementsByClassName(this.sa),b=0;b<a.length;b++){var c=f.prototype.w(a[b]),d;for(d in c)c.hasOwnProperty(d)&&c[d]==this.data.argument&&
this.p.push(a[b])}return 1<=this.p.length};g.prototype.Pa=function(){var a=[];this.C=!1;for(var b in this.q)if(this.q.hasOwnProperty(b)){var c=this.q[b];if(!c.b("isAdded")){var d=c.position()-window.innerHeight;window.pageYOffset>=d?a.push(c.ra()):this.C=!0}}return a};g.prototype.U=function(){var a=this.Pa();this.C||this.Da();return a};g.prototype.N=function(a){if(0<a.length){for(var b=0;b<a.length;b++)window.ebis.X(a[b]);window.ebis.v()}};g.prototype.da=function(){var a=function(a){return function(){var c=
a.U();a.N(c)}}(this);window.addEventListener?window.addEventListener(this.event,a,!1):window.attachEvent&&window.attachEvent("on"+this.event,a);this.n[this.R]={element:window,event:this.event,e:a,capture:!1};this.R++};g.prototype.Da=function(){if(this.e in this.n){var a=this.n[this.e];a.element.removeEventListener?a.element.removeEventListener(a.event,a.e,a.capture):a.element.detachEvent&&a.element.detachEvent("on"+a.event,a.e);delete this.n[this.e]}};n.prototype.b=function(a,b){if(b)return this.l.dataset[a]=
b,!0;var c=this.l.dataset,d;for(d in c)if(c.hasOwnProperty(d)&&d==a)return this.l.dataset[a];return""};n.prototype.position=function(){return this.l.offsetTop};n.prototype.ra=function(){var a={type:"pv"};this.b("isAdded",!0);for(var b in this.j)if(this.j.hasOwnProperty(b)){var c;c=this.j[b]==this.T?Math.round((new Date-this.s)/100)/10:this.b(this.j[b]);a[this.j[b]]=c}return a};f.prototype.B(l,k);l.prototype.f=function(){this.Ja();this.Ia()};l.prototype.Ja=function(){document.addEventListener("click",
function(a){var b=window.ebis,c={};a=a.target;for(var d=100;a&&0<d;d--){if(a.href&&a.nodeName.match(/^a(?:rea)?$/i)){c=a;break}a=a.parentNode}("http:"==c.protocol||"https:"==c.protocol)&&b.W(c.href)&&(b=b.D(c.href))&&(c.href=b)},!1)};l.prototype.Ia=function(){document.addEventListener("submit",function(a){var b=window.ebis;if((a=a.target)&&a.action&&b.W(a.action))if("get"==a.method.toLowerCase()){var c=document.createElement("input");c.type="hidden";c.name="_ebx";c.value=b.O();a.appendChild(c)}else"post"==
a.method.toLowerCase()&&(b=b.D(a.action))&&(a.action=b)},!1)};var q={Ca:!0,u:!1,pa:!0},r=[m,g];q.u&&r.push(l);window.ebis=new d(window.ebis.b||window.ebis,q,r,window.ebis.g)})();
